Documentation update + cleanup
FrendsPlatform/Frends.Excel pull request #13
Opened 2022-08-05 05:07 UTC by ttossavainen

2022-08-05 07:46 UTC, jefim requested changes

2022-08-05 07:46 UTC, jefim commented on .github/workflows/ConvertToCSV_build_and_test_on_main.yml
> +name: ConvertToCSV_build_main
I think that we can actually remove the underscores here, would be prettier :)

2022-08-05 07:46 UTC, jefim commented on .github/workflows/ConvertToCSV_build_and_test_on_push.yml
> +name: ConvertToCSV_build_test
Lets drop the underscores

2022-08-05 07:46 UTC, jefim commented on .github/workflows/ConvertToCSV_release.yml
> +name: ConvertToCSV_release
Lets drop the underscores

2022-08-05 07:46 UTC, jefim commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV.Tests/ExcelConvertTests.cs
> +    // Cat image in example files is from Pixbay.com. It is licenced in CC0 Public Domain (Free for commercial use, No attribution required). It is uploaded by Ben_Kerckx https://pixabay.com/en/cat-a
Lets not have such long lines. Ideally code and comments should fit into range of 120-160 chars. This line is too long.

2022-08-05 07:46 UTC, jefim commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV.Tests/ExcelConvertTests.cs
> +    /// Test converting all worksheets of xls file to csv.
No need for comments for unit tests. Only case to have a comment here is if the test is very complex and needs additional explanation.

2022-08-05 07:46 UTC, jefim commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV.Tests/ExcelConvertTests.cs
> +    /// Test converting all worksheets of xlsx file to csv.
No need for comments for unit tests.

2022-08-05 07:46 UTC, jefim commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV.Tests/ExcelConvertTests.cs
> +    /// Test converting one worksheet of xls file to csv.
No need for comments for unit tests.

2022-08-05 07:46 UTC, jefim commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV.Tests/ExcelConvertTests.cs
> +    /// Test converting one worksheet of xls file to csv.
No need for comments for unit tests.

2022-08-05 07:46 UTC, jefim commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV.Tests/ExcelConvertTests.cs
> +    /// Try to convert a file that does not exist
No need for comments for unit tests.

2022-08-05 07:46 UTC, jefim commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV/Definitions/DateFormats.cs
>      /// default value
Please specify the actual formats used. You can actually go to the ConvertToJSON branch / PR and copy from there. I have already done this there and I believe it is the same here.

2022-08-05 07:46 UTC, jefim commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV/Definitions/DateFormats.cs
>      /// day/month/year
Needs better comment

2022-08-05 07:46 UTC, jefim commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV/Definitions/DateFormats.cs
>      /// month/day/year
Needs better comment

2022-08-05 07:46 UTC, jefim commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV/Definitions/DateFormats.cs
>      /// year/month/day
Needs better comment

2022-08-05 07:46 UTC, jefim commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV/Definitions/Options.cs
> +    /// <example>&#59;</example>
I think that you can just use a semicolon instead of this HTML entity for it.

2022-08-05 07:46 UTC, jefim commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV/Excel.cs
> +            if (options.ReadOnlyWorkSheetWithName != null && (options.ReadOnlyWorkSheetWithName.Contains(table.TableName) || options.ReadOnlyWorkSheetWithName.Length == 0))
Won't this actually require the ReadOnlyWorkSheet to always be not null? I think that even if we see a null in this field then we should assume that we should handle all sheets.

2022-08-05 07:46 UTC, jefim commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV.csproj
>      <Company>Frends</Company>
Please add a setting to include the FrendsTaskMetadata.json in the nuget package.

2022-08-10 06:41 UTC, jefim requested changes

2022-08-10 06:54 UTC, ttossavainen commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV.Tests/ExcelConvertTests.cs
> +        if (_input.Path != null)
They were just for quick&easy fix to Visual Studio's CS8694 warnings.

2022-08-10 06:55 UTC, ttossavainen commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV.Tests/ExcelConvertTests.cs
> +        if (_input.Path != null)
They were just for quick&easy fix to Visual Studio's CS8694 warnings.

2022-08-10 06:55 UTC, ttossavainen commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV.Tests/ExcelConvertTests.cs
> +        if (_input.Path != null)
They were just for quick&easy fix to Visual Studio's CS8694 warnings.

2022-08-10 06:56 UTC, ttossavainen commented on Frends.Excel.ConvertToCSV/Frends.Excel.ConvertToCSV.Tests/ExcelConvertTests.cs
> +        if (_input.Path != null)
They were just for quick&easy fix to Visual Studio's CS8694 warnings.

2022-08-10 08:09 UTC, jefim approved these changes

2022-08-10 08:09 UTC, merged